export const DESCRIPTION_MAX_LENGTH = 120;

export const TEMPORARY_SAVE_INTERVAL_TIME = 10000;

export const MY_TAG_MAX_COUNT = 15;

export const SEARCH_RESULT_TIME = 500;

export const MAX_PROFILE_IMAGE_BYTE = 2097152;

export const MAX_IMAGE_BYTE = 5242880;

export const MEMO_NUMBER_PER_PAGE_FOR_INFINITY_SCROLL = 20;
export const SERIES_NUMBER_PER_PAGE_FOR_INFINITY_SCROLL = 20;
export const QUESTION_NUMBER_PER_PAGE_FOR_INFINITY_SCROLL = 20;
