import Header from '@/components/Header';
import '@/styles/globals.css';
import '@/styles/prosemirror.css';
import { Inter } from 'next/font/google';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex flex-col w-full max-w-screen-xl mx-auto">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
